
version: '3'
services:

  backend:
    build: ./
    container_name: backend-nestjs
    command: npm run start:dev
    ports:
      - 8080:8000
    depends_on:
      - db
  db:
    image: postgres:13.4
    restart: always
    environment:
      POSTGRES_DB: WhoYes
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
    ports:
      - 5400:5432
    volumes:
      - ./pg_data:/var/lib/postgresql/data

