version: '3'
services:
  db:
    image: postgres:13.4
    restart: always
    container_name: database-postgres
    environment:
      POSTGRES_DB: WhoYes
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
    ports:
      - 5432:5432
    volumes:
      - ./pg_data:/var/lib/postgresql/data

  backend:
    build: ./
    container_name: backend-nestjs
    command: npm run start:dev
    ports:
      - 8000:8000
    depends_on:
      - database

volumes:
  pg_data: